import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightgreen" }}>
          <p> This is a header </p>
        </header>
        {children}
        <footer style={{ backgroundColor: "lightgreen" }}>
          <p> This is a footer </p>
          <img src="/image.png" width={400}/>
        </footer>
      </body>
    </html>
  );
}
